#ifndef KISEKI_HAIRSIM_INCLUDE_HAIRSIM_CONSTRAINTS_H_
#define KISEKI_HAIRSIM_INCLUDE_HAIRSIM_CONSTRAINTS_H_

namespace hairsim {

struct Constraint {

};

}

#endif // KISEKI_HAIRSIM_INCLUDE_HAIRSIM_CONSTRAINTS_H_