//
// Created by creeper on 10/22/24.
//

#ifndef KISEKI_FEM_INCLUDE_FEM_PRIMITIVES_ELASTIC_SPHERE_H_
#define KISEKI_FEM_INCLUDE_FEM_PRIMITIVES_ELASTIC_SPHERE_H_
namespace fem {

struct ElasticSphere {

};

}
#endif //KISEKI_FEM_INCLUDE_FEM_PRIMITIVES_ELASTIC_SPHERE_H_
