//
// Created by creeper on 10/22/24.
//

#ifndef KISEKI_FEM_INCLUDE_FEM_PRIMITIVES_ELASTIC_STRING_H_
#define KISEKI_FEM_INCLUDE_FEM_PRIMITIVES_ELASTIC_STRING_H_
namespace fem {
struct ElasticString {

};
}
#endif //KISEKI_FEM_INCLUDE_FEM_PRIMITIVES_ELASTIC_STRING_H_
